[package]
name = "rust_async_await"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking"] }
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }

